name: Install and test package
on: push
jobs:
  nodejs:
    name: Node.js
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [^10, ^12, ^14]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --no-audit
      - run: npm test
